### ISSUE TITLE
Module activation breaks CLI commands

### ISSUE THREAD

**Issue by alessandromassobrio** [renatocason/magento2-module-mq-amqp#1]
After activating the module the [InvalidArgumentException] error is returned every time a CLI command is fired

**Comment by renatocason** [comment]
Hi @ale-at-shake,

I just tested the extension on Magento 2.1.9 / PHP 7.0.19 and everything is working as expected.
Could you try to empty the content of the var folder and, if you are using Redis for caching, to do a flush manually?

Thanks,
Renato

**Comment by alessandromassobrio** [comment]
Hi Renato,

I required the modules via composer on Magento 2.1.7 set on developer mode, the reported issue appeared after run the commands `bin/magento module:enable Rcason_MqAmqp` `bin/magento setup:upgrade` `bin/magento setup:di:compile`. Indeed, always on Magento 2.1.7, but with default mode enabled, all is working as expected. Can you confirm the same issue as for the developer mode?

Thanks,
Alessandro

**Comment by alessandromassobrio** [comment]
Thanks for the fix. [Release 0.1.1](https://github.com/renatocason/magento2-module-mq/tree/0.1.1) works perfectly in developer mode.

**Comment by renatocason** [comment]
Hi @ale-at-shake,

Great, thanks for your feedback!

Renato
