### ISSUE TITLE
Invalid Schema error

### ISSUE THREAD

**Issue by alessandromassobrio** [renatocason/magento2-module-mq-amqp#2]
On Magento CE 2.1.7 and 2.1.9, after `bin/magento setup:upgrade` the following error is generated in CLI. 

```
[Exception]                                                                                                                                                      
  Warning: DOMDocument::schemaValidate(): Invalid Schema in /vendor/magento/framework/Config/Dom.php on line 311  
```

Running `setup:db-schema:upgrade` and `magento setup:db-data:upgrade`, or even manually fix the schema version in db don't cause the error to disappear in CLI.

**Comment by renatocason** [comment]
Hi @ale-at-shake,

I don't get this issue on a vanilla Magento 2.1.9 / PHP 7.0.19, could you provide additional details?
For instance, if any other module is defining a queue?
The only situation where `setup:upgrade` should break is when a queue is defined, but the connection to RabbitMQ is not configured.

Thanks,
Renato

**Comment by grafikchaos** [comment]
I have the same issue with Magento CE 2.1.8 (vanilla sandbox) and a Magento 2.1.9 project. Tested with PHP 7.0.22 and PHP 5.6.35. Went through other modules and am not seeing another queue being defined. 

Currently I have no queues defined and no RabbitMQ configuration.

**Comment by renatocason** [comment]
Hi @grafikchaos,

This issue should be fixed with version 0.1.1 of magento2-module-mq, can you make sure you are using that?

Thanks,
Renato

**Comment by grafikchaos** [comment]
Hi @renatocason,

I was using 0.1.0 of the magento2-module-mq module. Upgrading it to 0.1.1 fixed my issue. Thank you!

**Comment by renatocason** [comment]
Hi @grafikchaos,

Great news, thanks for the feedback!

Regards,
Renato
